version: '3.8'

services:
  database:
    image: postgres:latest
    volumes:
      - ./docker/postgres-multiple-databases.sh:/docker-entrypoint-initdb.d/postgres-multiple-databases.sh
    restart: always
    hostname: campaigns
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespsw
      - POSTGRES_MULTIPLE_DATABASES=jpaexample,jpaexample_test
